/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisc' at '7/9/16 1:05 PM' with Gradle 2.12
 *
 * @author luisc, @date 7/9/16 1:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
